/**
 * This code was generated by Builder.io
 */
import React from "react";

function AutomateReporting() {
  return (
    <section className="mt-24 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-3xl font-semibold text-center text-slate-950">
        Automate Reporting
      </h2>
      <p className="mt-5 text-lg leading-none text-center text-slate-950 text-opacity-80 max-md:max-w-full">
        Rimba integrates with your tools seamlessly, making data consolidation
        easy every step of the way.
      </p>
      <div className="flex flex-wrap items-center mt-16 w-full text-base font-medium text-center text-white max-w-[1180px] max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col self-stretch my-auto text-sm">
          <div className="flex w-full">
            <div className="gap-2.5 self-stretch px-8 py-4 bg-slate-950 min-h-[50px] rounded-[140px] max-md:px-5">
              Compliance Requir...
            </div>
            <div className="shrink-0 my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
          <div className="flex mt-8 w-full">
            <div className="gap-2.5 self-stretch px-8 py-4 bg-slate-950 min-h-[50px] rounded-[140px] max-md:px-5">
              External Data
            </div>
            <div className="shrink-0 my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
          <div className="flex mt-8 w-full">
            <div className="gap-2.5 self-stretch px-8 py-4 bg-slate-950 min-h-[50px] rounded-[140px] max-md:px-5">
              Internal Data
            </div>
            <div className="shrink-0 my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
        </div>
        <div className="shrink-0 self-stretch my-auto w-0.5 border-2 border-teal-700 border-solid h-[162px]" />
        <div className="shrink-0 self-start mt-36 h-0.5 border-2 border-teal-700 border-solid w-[25px] max-md:mt-10" />
        <div className="gap-2.5 self-stretch px-8 py-4 my-auto whitespace-nowrap bg-teal-700 min-h-[50px] rounded-[140px] max-md:px-5">
          Rimba
        </div>
        <div className="z-10 shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px] max-md:-mr-0.5" />
        <div className="shrink-0 self-stretch my-auto w-0.5 border-2 border-teal-700 border-solid h-[242px]" />
        <div className="flex flex-col self-stretch text-sm text-teal-700">
          <div className="flex items-center w-full">
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
            <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
              Mass Balance
            </div>
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
          <div className="flex items-center mt-8 w-full">
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
            <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
              Carbon Intensity
            </div>
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
          <div className="flex items-center mt-8 w-full">
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
            <div className="gap-2.5 self-stretch py-4 pr-4 pl-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px]">
              Fuel Transactions Report
            </div>
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
          <div className="flex items-center mt-8 w-full">
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
            <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
              Audit Preparation
            </div>
            <div className="shrink-0 self-stretch my-auto h-0.5 border-2 border-teal-700 border-solid w-[25px]" />
          </div>
        </div>
        <div className="shrink-0 self-stretch my-auto w-0.5 border-2 border-teal-700 border-solid h-[242px]" />
        <div className="shrink-0 self-start mt-36 h-0.5 border-2 border-teal-700 border-solid w-[25px] max-md:mt-10" />
        <div className="gap-2.5 self-stretch px-8 py-4 my-auto bg-teal-700 min-h-[50px] rounded-[140px] max-md:px-5">
          Audit with Ease
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2faf4cceb39862c44ba4a89cf35583ab301116afff83c98247fd19973298d645?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          className="object-contain shrink-0 self-stretch my-auto rounded-none w-[30px]"
          alt="Arrow icon"
        />
        <div className="gap-2.5 self-stretch py-4 pr-5 pl-6 my-auto bg-teal-700 min-h-[50px] rounded-[140px] max-md:px-5">
          Reporting Simplified
        </div>
      </div>
      <div className="flex flex-wrap gap-2 mt-12 ml-2.5 w-full text-sm font-medium text-center text-teal-700 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Data Reconciliation
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Automate Workflows
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Generate Report...
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Monitor Compliance
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
          Simplify Audit
        </div>
      </div>
    </section>
  );
}

export default AutomateReporting;
