/**
 * This code was generated by Builder.io
 */
import React from "react";
import Chart from './Chart';
function AutomateReporting() {
  return (
    <section className="mt-24 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-3xl font-semibold text-center text-slate-950">
        Automate Reporting
      </h2>
      <p className="mt-5 text-lg leading-none text-center text-slate-950 text-opacity-80 max-md:max-w-full mb-10">
        Rimba integrates with your tools seamlessly, making data consolidation
        easy every step of the way.
      </p>
      <Chart></Chart>
      {/* <div className="flex flex-wrap gap-2 mt-12 ml-2.5 w-full text-sm font-medium text-center text-teal-700 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Data Reconciliation
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Automate Workflows
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Generate Report...
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="flex">
          <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
            Monitor Compliance
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2514c996921260bda4224730607e94f940ef3948adc1dabd79ce1fc75a83d9a2?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            className="object-contain shrink-0 my-auto aspect-[4.37] w-[35px]"
            alt="Arrow icon"
          />
        </div>
        <div className="gap-2.5 self-stretch px-8 py-4 bg-teal-700 bg-opacity-10 min-h-[50px] rounded-[140px] max-md:px-5">
          Simplify Audit
        </div>
      </div> */}
    </section>
  );
}

export default AutomateReporting;
