/**
 * This code was generated by Builder.io
 */
import React from "react";

const complianceData = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e87a1f99d8f9c730e5b8cb52cffc6d0e57d49cf582fb514a44b2ec03c8b3c2c7?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "LCFS (Low Carbon Fuel Standard)",
    description:
      "A regulatory program in California designed to reduce the carbon intensity (CI) of fuels. It requires fuel providers to...",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3a5c960c5727308014f0c19429fdd97c597c27e5b88e19da2b75b2d5d876dda5?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "RFS (Renewable Fuel Standard)",
    description:
      "A U.S. federal mandate that sets annual renewable volume obligations (RVOs) for fuel refiners and importers. Compliance...",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/fb70a025cc9383e5ff61e1da8360bd3078ae6a2a7090f9bb0047e352e0984b49?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "ISCC (International Sustainability & Carbon C...",
    description:
      "A certification system that ensures compliance with sustainability and traceability requirements in biofuel sup...",
  },
];

function ComplianceCard({ image, title, description }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow pb-8 w-full rounded-3xl bg-white bg-opacity-40 shadow-[0px_0px_20px_rgba(209,234,232,0.5)] max-md:mt-10">
        <div className="flex flex-col justify-center px-20 py-12 bg-slate-50 rounded-[30px_30px_0px_0px] max-md:px-5">
          <img
            loading="lazy"
            src={image}
            className="object-contain aspect-[1.32] w-[212px]"
            alt={title}
          />
        </div>
        <div className="flex flex-col items-start px-8 mt-8 w-full text-base max-md:px-5">
          <h3 className="text-xl font-semibold leading-8 text-stone-900">
            {title}
          </h3>
          <p className="self-stretch mt-3.5 leading-6 text-black text-opacity-60">
            {description}
          </p>
          <div className="flex gap-2.5 mt-5 font-medium text-teal-700">
            <div className="grow">Read More</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e752addf5fb093d4463d69d5bacc21e3958ff5cb378ba3dbcf141c4c078695?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
              className="object-contain shrink-0 my-auto aspect-[1.21] w-[17px]"
              alt="Read more arrow"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function ComplianceRequirements() {
  return (
    <section className="mt-24 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-3xl font-semibold text-center text-slate-950">
        Compliance Requirements
      </h2>
      <p className="mt-5 text-lg leading-6 text-center text-slate-950 text-opacity-80 w-[952px] max-md:max-w-full">
        Mandates and incentives are drivers of the bioenergy industry. To
        operate, suppliers, producers, and off-takers have to comply with
        compliance requirements in each market.
      </p>
      <div className="mt-16 w-full max-w-[1180px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {complianceData.map((item, index) => (
            <ComplianceCard key={index} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default ComplianceRequirements;
