/**
 * This code was generated by Builder.io
 */
import React from "react";
import { useState } from "react";
import Cross from '../../img/cross.svg';
const complianceData = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e87a1f99d8f9c730e5b8cb52cffc6d0e57d49cf582fb514a44b2ec03c8b3c2c7?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "LCFS (Low Carbon Fuel Standard)",
    description:
      "A regulatory program in California designed to reduce the carbon intensity (CI) of fuels. It requires fuel providers to...",
    long_description:"A regulatory program in California designed to reduce the carbon intensity (CI) of fuels. It requires fuel providers to meet annual CI targets and offers tradable LCFS credits to those who produce or import fuels with lower CI, enabling compliance through credit trading. Rimba helps automate LCFS compliance reporting by converting operational data into the specific reporting formats required by the program."
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/3a5c960c5727308014f0c19429fdd97c597c27e5b88e19da2b75b2d5d876dda5?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "RFS (Renewable Fuel Standard)",
    description:
      "A U.S. federal mandate that sets annual renewable volume obligations (RVOs) for fuel refiners and importers. Compliance...",
      long_description:"A U.S. federal mandate that sets annual renewable volume obligations (RVOs) for fuel refiners and importers. Compliance is achieved by generating or acquiring Renewable Identification Numbers (RINs), which are tradable credits tied to renewable fuel production. Rimba streamlines RFS compliance by transforming operational data into RIN generation and reporting formats."
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/fb70a025cc9383e5ff61e1da8360bd3078ae6a2a7090f9bb0047e352e0984b49?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "ISCC (International Sustainability & Carbon C...",
    description:
      "A certification system that ensures compliance with sustainability and traceability requirements in biofuel sup...",
      long_description : "A certification system that ensures compliance with sustainability and traceability requirements in biofuel supply chains. It supports compliance with regulations like the EU RED and enables the generation of sustainability credits to demonstrate adherence to greenhouse gas (GHG) reduction goals. Rimba automates ISCC compliance by processing operational data and evidence into audit-ready sustainability reports."
  },
];

function ComplianceCard({ image, title, description,long_description }) {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const toggleModal = () => {
    setIsModalOpen(!isModalOpen);
  };
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow pb-8 w-full rounded-3xl bg-white bg-opacity-40 shadow-[0px_0px_20px_rgba(209,234,232,0.5)] max-md:mt-10">
        <div className="flex flex-col justify-center px-20 py-12 bg-slate-50 rounded-[30px_30px_0px_0px] max-md:px-5">
          <img
            loading="lazy"
            src={image}
            className="object-contain aspect-[1.32] w-[212px]"
            alt={title}
          />
        </div>
        <div className="flex flex-col items-start px-8 mt-8 w-full text-base max-md:px-5">
          <h3 className="text-xl font-semibold leading-8 text-stone-900">
            {title}
          </h3>
          <p className="self-stretch mt-3.5 leading-6 text-black text-opacity-60">
            {description}
          </p>
          <button className="flex gap-2.5 mt-5 font-medium text-teal-700" onClick={toggleModal}>
            <div className="grow">Read More</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e752addf5fb093d4463d69d5bacc21e3958ff5cb378ba3dbcf141c4c078695?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
              className="object-contain shrink-0 my-auto aspect-[1.21] w-[17px]"
              alt="Read more arrow"
            />
          </button>
        </div>
      </div>
      {isModalOpen && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
          <div className="bg-white p-8 rounded-lg max-w-md flex flex-col h-1/2 w-[640px] relative">
          <div className="flex justify-center mb-4">
          <img
            loading="lazy"
            src={image}
            className="object-contain aspect-[1.32] w-[212px]"
            alt={title}
          />
            <button
          className="absolute top-2 right-2 text-gray-500 hover:text-gray-700"
          onClick={toggleModal}
        >
        <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path id="Vector" d="M10.5862 8.99904L17.6693 1.92716C17.8811 1.71545 18 1.42831 18 1.12891C18 0.829501 17.8811 0.54236 17.6693 0.330649C17.4576 0.118938 17.1705 0 16.8711 0C16.5717 0 16.2845 0.118938 16.0728 0.330649L9.00096 7.41377L1.92908 0.330649C1.71737 0.118938 1.43023 2.65824e-07 1.13082 2.68055e-07C0.83142 2.70286e-07 0.544278 0.118938 0.332568 0.330649C0.120857 0.54236 0.00191901 0.829501 0.00191901 1.12891C0.001919 1.42831 0.120857 1.71545 0.332568 1.92716L7.41569 8.99904L0.332568 16.0709C0.227188 16.1754 0.143547 16.2998 0.0864671 16.4368C0.0293876 16.5738 0 16.7208 0 16.8692C0 17.0176 0.0293876 17.1645 0.0864671 17.3016C0.143547 17.4386 0.227188 17.5629 0.332568 17.6674C0.437086 17.7728 0.561436 17.8565 0.698443 17.9135C0.835449 17.9706 0.982403 18 1.13082 18C1.27925 18 1.4262 17.9706 1.56321 17.9135C1.70021 17.8565 1.82456 17.7728 1.92908 17.6674L9.00096 10.5843L16.0728 17.6674C16.1774 17.7728 16.3017 17.8565 16.4387 17.9135C16.5757 17.9706 16.7227 18 16.8711 18C17.0195 18 17.1665 17.9706 17.3035 17.9135C17.4405 17.8565 17.5648 17.7728 17.6693 17.6674C17.7747 17.5629 17.8584 17.4386 17.9155 17.3016C17.9725 17.1645 18.0019 17.0176 18.0019 16.8692C18.0019 16.7208 17.9725 16.5738 17.9155 16.4368C17.8584 16.2998 17.7747 16.1754 17.6693 16.0709L10.5862 8.99904Z" fill="#040A27"/>
</svg>
        </button>
          </div>
          <div>
            <h3 className="text-xl font-semibold">{title}</h3>
            <p className="mt-4">{long_description}</p>

          </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ComplianceRequirements() {
  return (
    <section className="mt-24 max-w-[1180px] max-md:mt-10 max-md:max-w-full">
      <h2 className="text-3xl font-semibold text-center text-slate-950">
        Compliance Requirements
      </h2>
      <p className="mt-5 text-lg leading-6 text-center text-slate-950 text-opacity-80 w-[952px] max-md:max-w-full">
        Mandates and incentives are drivers of the bioenergy industry. To
        operate, suppliers, producers, and off-takers have to comply with
        compliance requirements in each market.
      </p>
      <div className="mt-16 w-full max-w-[1180px] max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {complianceData.map((item, index) => (
            <ComplianceCard key={index} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default ComplianceRequirements;
