/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "../common/Header";
import Hero from "./Hero";
import TrustedBy from "./TrustedBy";
import ComplianceRequirements from "./ComplianceRequirements";
import AboutUs from "./AboutUs";
import OneCentralPlatform from "./OneCentralPlatform";
import CaseStudies from "./CaseStudies";
import HowItWorks from "./HowItWorks";
import AutomateReporting from "./AutomateReporting";
import FAQ from "../common/FAQ";
import ContactUs from "../common/ContactUs";
import GetStarted from "../common/GetStarted";
import Footer from "../common/Footer";

function HomePage() {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-white">
      <Header />
      <Hero />
      <TrustedBy />
      <ComplianceRequirements />
      <AboutUs />
      <OneCentralPlatform />
      <CaseStudies />
      <HowItWorks />
      <AutomateReporting />
      <FAQ />
      <ContactUs />
      <GetStarted />
      <Footer />
    </div>
  );
}

export default HomePage;
