/**
 * This code was generated by Builder.io
 */
import React from "react";

const steps = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6fd8100ab141ec86334cd9b180edf723662cb0da5e84ecb1fa93037e866fc1da?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Streamline your Data",
    description:
      "Streamline the collection and processing of large volumes of supply chain documents and operational data effortlessly.",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/2e1e30380cdadf246883fdf121b60be1fc2f91c51bd315ed7bc8929721965a78?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Transform",
    description:
      "Extract and transform operational data in any format into specific reports required by each compliance standards.",
  },
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/72d5d31459dec205234b1fb472922d8670465d99e7951c8fdc5cfb07534b748e?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Stay Informed with Real-Time Monitoring",
    description:
      "Monitor your input and production accurately by detecting gaps and anomalies early to generate credits accurately.",
  },
];

function StepCard({ image, title, description, index }) {
  const isEven = index % 2 === 0;
  return (
    <div className="mt-16 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {isEven ? (
          <>
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src={image}
                className="object-contain grow w-full rounded-3xl aspect-[1.61] max-md:mt-10 max-md:max-w-full"
                alt={title}
              />
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
                <h3 className="text-2xl font-semibold leading-none text-slate-950">
                  {title}
                </h3>
                <p className="self-stretch mt-4 text-lg leading-8 text-slate-950 text-opacity-80 max-md:max-w-full">
                  {description}
                </p>
                <button className="gap-2.5 self-stretch px-8 py-4 mt-8 text-sm font-medium text-center text-white bg-teal-700 rounded-xl min-h-[48px] max-md:px-5">
                  Learn More
                </button>
              </div>
            </div>
          </>
        ) : (
          <>
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
                <h3 className="text-2xl font-semibold leading-none text-slate-950">
                  {title}
                </h3>
                <p className="self-stretch mt-4 text-lg leading-8 text-slate-950 text-opacity-80 max-md:max-w-full">
                  {description}
                </p>
                <button className="gap-2.5 self-stretch px-8 py-4 mt-8 text-sm font-medium text-center text-white bg-teal-700 rounded-xl min-h-[48px] max-md:px-5">
                  Learn More
                </button>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src={image}
                className="object-contain grow w-full rounded-3xl aspect-[1.7] max-md:mt-10 max-md:max-w-full"
                alt={title}
              />
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function HowItWorks() {
  return (
    <section className="flex flex-col justify-center items-center self-stretch px-20 py-24 mt-24 w-full  shadow-[0px_4px_20px_rgba(209,234,232,0.3)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1180px] max-md:max-w-full">
        <h2 className="self-center text-3xl font-semibold text-center text-slate-950">
          How it works
        </h2>
        <p className="self-center mt-5 text-lg leading-none text-center text-slate-950 text-opacity-80 max-md:max-w-full">
          Rimba streamlines compliance management with a simple step by step
          intuitive process.
        </p>
        {steps.map((step, index) => (
          <StepCard key={index} {...step} index={index} />
        ))}
      </div>
    </section>
  );
}

export default HowItWorks;
