/**
 * This code was generated by Builder.io
 */
import React from "react";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e08d741e-3ae0-4da9-8c65-7b5e96223c80?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Real-Time Insights",
    description:
      "Gain real-time insights to stay informed and make proactive decisions.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d18aa899-4afc-4298-9748-292b78a08791?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Risk Mitigation",
    description:
      "Streamline document processing to reduce risk and ensure compliance.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ff87df3c-7b2e-4cb2-8852-f909a518d3af?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Audit Preparation",
    description:
      "Simplify audits and compliance with verified supply chain data.",
  },
];

function FeatureCard({ icon, title, description }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow items-start p-8 w-full rounded-3xl bg-cyan-950 max-md:px-5 max-md:mt-10">
        <img
          loading="lazy"
          src={icon}
          className="object-contain w-16 h-16 bg-white aspect-square rounded-[60px]"
          alt={`${title} icon`}
        />
        <h3 className="mt-9 text-xl font-semibold text-white">{title}</h3>
        <p className="self-stretch mt-3 text-base leading-6 text-white text-opacity-80">
          {description}
        </p>
      </div>
    </div>
  );
}

function OneCentralPlatform() {
  return (
    <section className="flex flex-col self-stretch w-full bg-slate-950 bg-opacity-90 shadow-[0px_4px_20px_rgba(209,234,232,0.3)] max-md:max-w-full">
      <div className="flex relative flex-col justify-center items-center px-20 py-24 w-full min-h-[640px] max-md:px-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bd8fafe53fd79f9fe3248945f219eb70273f9db3428ef5020c7b689630930337?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          className="object-cover absolute inset-0 size-full"
          alt="Background image"
        />
        <div className="flex relative flex-col items-center w-full max-w-[1180px] max-md:max-w-full">
          <h2 className="text-3xl font-semibold text-center text-white">
            One Central Platform
          </h2>
          <p className="mt-5 text-base leading-7 text-center text-white w-[952px] max-md:max-w-full">
            Gain complete visibility into your compliance data, how it's
            processed, and how it supports credit generation—all while
            consolidating reporting for multiple compliance programs on one
            seamless platform.
          </p>
          <div className="self-stretch mt-20 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              {features.map((feature, index) => (
                <FeatureCard key={index} {...feature} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default OneCentralPlatform;
