/**
 * This code was generated by Builder.io
 */
import React from "react";

function TrustedBy() {
  return (
    <section className="px-12 py-10 mt-24 w-full rounded-3xl bg-white bg-opacity-40 max-w-[1180px] shadow-[0px_0px_20px_rgba(209,234,232,0.5)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[29%] max-md:ml-0 max-md:w-full">
          <h2 className="self-stretch my-auto text-xl font-bold leading-8 text-slate-950 max-md:mt-10">
            Trusted by in the bioenergy supply chain
          </h2>
        </div>
        <div className="flex flex-col ml-5 w-[71%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-wrap gap-10 max-md:mt-10">
            <div className="flex gap-5 my-auto text-2xl font-semibold leading-none text-teal-700">
              <div className="grow my-auto border-slate-50">Member of</div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/caf09f1323899c08aa03fd356839bbefc9927aa0c2592151cf1742fc0942a923?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
                className="object-contain shrink-0 aspect-[2.87] w-[92px]"
                alt="Member organization logo"
              />
            </div>
            <div className="flex flex-auto gap-10">
              <div className="shrink-0 my-auto w-px border border-solid border-slate-950 border-opacity-10 h-[50px]"></div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/2ab7e680158af43014b489125d8a6aaaf0f34dd349c84c15df9c185e830428d0?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
                className="object-contain shrink-0 aspect-square w-[60px]"
                alt="Partner logo 1"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/10c2776aff06b56a3b6a334c9b0180546179fbbd62dfa08b4fe0c577e27ea816?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
                className="object-contain shrink-0 aspect-square w-[60px]"
                alt="Partner logo 2"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/27d6a58a25a80bcbdc2d39cef6408ac481751fae0d84a3a1d9fb6b64adfe21c4?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
                className="object-contain shrink-0 aspect-square w-[60px]"
                alt="Partner logo 3"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/2dbbec32da4218de470ed4def026537fdf438861e2e3606ef9541cdf99b1efb3?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
                className="object-contain shrink-0 aspect-square w-[60px]"
                alt="Partner logo 4"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default TrustedBy;
