/**
 * This code was generated by Builder.io
 */
import React from "react";

export const CaseStudyCard = ({ image, title, description, id }) => {
  return (
    <article className="flex flex-col grow pb-8 w-full text-base rounded-3xl bg-white bg-opacity-40 shadow-[0px_0px_20px_rgba(209,234,232,0.5)] max-md:mt-10">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain w-full aspect-[1.41] rounded-[30px_30px_0px_0px]"
      />
      <div className="flex flex-col items-start px-8 mt-8 w-full max-md:px-5">
        <h3 className="text-xl font-semibold leading-8 text-stone-900">
          {title}
        </h3>
        <p className="self-stretch mt-3.5 leading-6 text-black text-opacity-60">
          {description}
        </p>
        <a href={`/case-studies/${id}`} className="flex gap-2.5 mt-5 font-medium text-teal-700">
          <span className="grow">View Details</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e752addf5fb093d4463d69d5bacc21e3958ff5cb378ba3dbcf141c4c078695?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            alt=""
            className="object-contain shrink-0 my-auto aspect-[1.21] w-[17px]"
          />
        </a>
      </div>
    </article>
  );
};
