/**
 * This code was generated by Builder.io
 */
import React from "react";

export const NewsletterForm = () => {
  return (
    <form className="flex flex-col p-11 font-medium rounded-3xl bg-white bg-opacity-10 max-md:px-5 max-md:max-w-full">
      <h2 className="self-start text-3xl font-semibold">Get Started</h2>
      <label htmlFor="email" className="self-start mt-10 text-lg">
        Email
      </label>
      <input
        type="email"
        id="email"
        className="px-5 py-5 mt-5 text-sm bg-white rounded-xl text-neutral-400 max-md:max-w-full"
        placeholder="Enter your email"
        aria-label="Enter your email"
      />
      <button
        type="submit"
        className="gap-2.5 self-stretch px-8 py-5 mt-8 text-base text-center text-white bg-teal-700 rounded-xl min-h-[54px] max-md:px-5"
      >
        Request A Demo
      </button>
    </form>
  );
};
