/**
 * This code was generated by Builder.io
 */
import React from "react";

const faqItems = [
  "What is Rimba?",
  "Who can benefit from using Rimba?",
  "What types of data does Rimba process?",
  "Which regulatory standards does Rimba support?",
  "How does Rimba help with audits?",
];

function FAQ() {
  return (
    <section className="w-full max-w-[1180px]">
      <h2 className="mt-24 text-3xl font-semibold text-center text-slate-950 max-md:mt-10 max-md:max-w-full">
        Frequently Asked Questions (FAQ)
      </h2>
      {faqItems.map((question, index) => (
        <button
          key={index}
          className="flex flex-wrap gap-5 justify-between px-8 py-7 mt-6 w-full text-base font-medium rounded-3xl bg-white bg-opacity-40 text-slate-950 max-md:px-5 max-md:max-w-full"
          aria-expanded="false"
        >
          <span>{question}</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/09fbe09aff55735c3b1798b40356aca1f563594a3f292574c71ece89d3a74a1c?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
            alt=""
            className="object-contain shrink-0 my-auto aspect-[0.61] w-[11px]"
          />
        </button>
      ))}
      <button className="flex gap-3 mt-8 max-w-full text-base font-medium text-teal-700 w-[150px]">
        <span className="grow">View More FAQs</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e752addf5fb093d4463d69d5bacc21e3958ff5cb378ba3dbcf141c4c078695?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[1.21] w-[17px]"
        />
      </button>
    </section>
  );
}

export default FAQ;
