/**
 * This code was generated by Builder.io
 */
import React from "react";

const features = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8d1fb713-0a7c-47e9-b437-beb2c4fab0b7?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Track",
    description: "Automate supply chain traceability from feedstock to fuels.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/07b0652e-5a91-4737-8ac3-90184f30a260?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Measure",
    description: "Simplify process to test and measure carbon intensity.",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/03846bd6-882f-4bff-a241-2230ea552352?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
    title: "Report",
    description:
      "Automate data processing and detect anomalies, gaps in your data.",
  },
];

function Features() {
  return (
    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col self-stretch p-12 m-auto w-full bg-white rounded-3xl shadow-[0px_4px_20px_rgba(209,234,232,0.3)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
        {features.map((feature, index) => (
          <div key={index} className={`flex gap-6 ${index > 0 ? "mt-10" : ""}`}>
            <img
              loading="lazy"
              src={feature.icon}
              alt={`${feature.title} icon`}
              className="object-contain shrink-0 self-start bg-white rounded-2xl aspect-square h-[62px] shadow-[0px_4px_20px_rgba(209,234,232,0.3)] w-[62px]"
            />
            <div className="flex flex-col grow shrink-0 basis-0 w-fit">
              <h3 className="self-start text-xl font-semibold text-slate-950">
                {feature.title}
              </h3>
              <p className="mt-2.5 text-sm leading-6 text-slate-950 text-opacity-80">
                {feature.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Features;
