/**
 * This code was generated by Builder.io
 */
import React from "react";

const footerLinks = [
  "Product",
  "Solutions",
  "Demo",
  "FAQ",
  "About Us",
  "Terms of Service",
  "Privacy Policy",
];

function Footer() {
  return (
    <footer className="w-full mt-24 max-md:mt-10">
      <div className="self-stretch w-full border-2 border-solid border-white border-opacity-10 min-h-[2px] max-md:max-w-full" />
      <div className="flex flex-wrap gap-5 justify-between mt-8 w-full max-w-screen-xl text-base max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e8ad748a54f94c069af740543875246a22c4373dcf42a71faecf8455f6770aab?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          alt="Rimba Logo"
          className="object-contain shrink-0 max-w-full aspect-[3.05] w-[122px]"
        />
        <nav className="flex flex-wrap gap-8 items-center my-auto max-md:max-w-full">
          {footerLinks.map((link, index) => (
            <a
              key={index}
              href="#"
              className="self-stretch my-auto text-white hover:text-teal-700"
            >
              {link}
            </a>
          ))}
        </nav>
      </div>
      <div className="shrink-0 mt-6 max-w-full h-0.5 border-2 border-solid border-white border-opacity-10 w-[1280px]" />
      <div className="flex flex-wrap gap-5 justify-between mt-6 w-full max-w-screen-xl text-sm leading-none text-white max-md:max-w-full">
        <p className="my-auto">2024 Rimba AI, Inc All Rights Reserved</p>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/179ab9a1c55525e441a99f7bd665f666fb2e5ef7c97c57cf3350163f0566ab49?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          alt="Social Media Links"
          className="object-contain shrink-0 max-w-full rounded-none aspect-[3.82] w-[130px]"
        />
      </div>
    </footer>
  );
}

export default Footer;
