/**
 * This code was generated by Builder.io
 */
import React from "react";

const stats = [
  { number: "5000+", label: "Managed Processes" },
  { number: "60+", label: "Active Clients" },
  { number: "300+", label: "Satisfied Users" },
  { number: "12+", label: "Team Members" },
];

function Stats() {
  return (
    <section className="flex flex-col justify-center items-center self-stretch px-16 py-12 mt-24 w-full text-center bg-slate-950 bg-opacity-90 shadow-[0px_4px_20px_rgba(209,234,232,0.3)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full max-w-[1140px] max-md:max-w-full">
        {stats.map((stat, index) => (
          <div key={index} className="flex flex-col">
            <div className="self-center text-4xl font-semibold leading-none text-white">
              {stat.number}
            </div>
            <div className="mt-4 text-xl text-white text-opacity-70">
              {stat.label}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Stats;
