/**
 * This code was generated by Builder.io
 */
import React from "react";

const FAQItem = ({ question }) => (
  <div className="flex flex-wrap gap-5 justify-between px-8 py-7 mt-6 w-full text-base font-medium rounded-3xl bg-white bg-opacity-40 max-w-[1180px] text-slate-950 max-md:px-5 max-md:max-w-full">
    <div>{question}</div>
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/09fbe09aff55735c3b1798b40356aca1f563594a3f292574c71ece89d3a74a1c?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
      alt=""
      className="object-contain shrink-0 my-auto aspect-[0.61] w-[11px]"
    />
  </div>
);

const FAQ = () => {
  const questions = [
    "What is Rimba?",
    "Who can benefit from using Rimba?",
    "What types of data does Rimba process?",
    "Which regulatory standards does Rimba support?",
    "How does Rimba help with audits?",
  ];

  return (
    <section className="mt-24 max-md:mt-10 max-md:max-w-full">
      <h2 className="text-3xl font-semibold text-center text-slate-950">
        Frequently Asked Questions (FAQ)
      </h2>
      {questions.map((question, index) => (
        <FAQItem key={index} question={question} />
      ))}
      <div className="flex gap-3 mt-8 max-w-full text-base font-medium text-teal-700 w-[150px]">
        <div className="grow">View More FAQs</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7e752addf5fb093d4463d69d5bacc21e3958ff5cb378ba3dbcf141c4c078695?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c"
          alt=""
          className="object-contain shrink-0 my-auto aspect-[1.21] w-[17px]"
        />
      </div>
    </section>
  );
};

export default FAQ;
