/**
 * This code was generated by Builder.io
 */
import React from "react";
import MainContent from "./MainContent";
// import Footer from "./Footer";
import GetStarted from "../common/GetStarted";
import Footer from "../common/Footer";
import Header from "../common/Header";

const HowIt = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-white">
      <Header></Header>
      <MainContent />
      <GetStarted/>
      <Footer />
    </div>
  );
};

export default HowIt;
