/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
// import Footer from "./Footer";
import GetStarted from "../HomePage/GetStarted";
import Footer from "../HomePage/Footer";

const HowIt = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-white">
      <Header />
      <MainContent />
      <GetStarted/>
      <Footer />
    </div>
  );
};

export default HowIt;
