/**
 * This code was generated by Builder.io
 */
import React from "react";
import HowItWorks from "./HowItWorks";
import ProcessSteps from "./ProcessSteps";
import FAQ from "../common/FAQ";
import ContactSection from "./ContactSection";
const MainContent = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center bg-white">
      <HowItWorks />
      <ProcessSteps />
      <FAQ />
      <ContactSection />
    </div>
  );
};

export default MainContent;
