/**
 * This code was generated by Builder.io
 */
import React from "react";

const ProcessStep = ({
  number,
  title,
  description,
  imageSrc,
  imageAlt,
  isReversed,
}) => {
  const contentOrder = isReversed ? "order-2" : "order-1";
  const imageOrder = isReversed ? "order-1" : "order-2";

  return (
    <div className="mt-16 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div
          className={`flex flex-col w-6/12 max-md:ml-0 max-md:w-full ${contentOrder}`}
        >
          <div className="flex flex-col mt-11 w-full max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-wrap gap-10 items-start self-start font-semibold max-md:max-w-full">
              <div className="self-end mt-16 text-2xl leading-none text-slate-950 max-md:mt-10">
                {title}
              </div>
              <div className="self-start text-8xl leading-snug text-center text-slate-950 text-opacity-10 max-md:text-4xl">
                {number}
              </div>
            </div>
            <p className="mt-4 text-lg leading-8 text-slate-950 text-opacity-80 max-md:max-w-full">
              {description}
            </p>
          </div>
        </div>
        <div
          className={`flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full ${imageOrder}`}
        >
          <img
            loading="lazy"
            src={imageSrc}
            alt={imageAlt}
            className="object-contain grow w-full rounded-3xl aspect-[1.61] max-md:mt-10 max-md:max-w-full"
          />
        </div>
      </div>
    </div>
  );
};

export default ProcessStep;
