/**
 * This code was generated by Builder.io
 */
import React from "react";
import ProcessStep from "./ProcessStep";

const ProcessSteps = () => {
  const steps = [
    {
      number: "1",
      title: "Streamline your Data",
      description:
        "Streamline the collection and processing of large volumes of supply chain documents and operational data effortlessly.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/6fd8100ab141ec86334cd9b180edf723662cb0da5e84ecb1fa93037e866fc1da?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
      imageAlt: "Data streamlining illustration",
      isReversed: false,
    },
    {
      number: "2",
      title: "Transform",
      description:
        "Extract and transform operational data in any format into specific reports required by each compliance standards.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2e1e30380cdadf246883fdf121b60be1fc2f91c51bd315ed7bc8929721965a78?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
      imageAlt: "Data transformation illustration",
      isReversed: true,
    },
    {
      number: "3",
      title: "Stay Informed with Real-Time Monitoring",
      description:
        "Monitor your input and production accurately by detecting gaps and anomalies early to generate credits accurately.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/72d5d31459dec205234b1fb472922d8670465d99e7951c8fdc5cfb07534b748e?placeholderIfAbsent=true&apiKey=fd087a8e03ab4599addc57757630651c",
      imageAlt: "Real-time monitoring illustration",
      isReversed: false,
    },
  ];

  return (
    <section className="flex flex-col justify-center items-center self-stretch px-20 py-24 mt-40 w-full  shadow-[0px_4px_20px_rgba(209,234,232,0.3)] max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1180px] max-md:max-w-full">
        <h2 className="self-center text-3xl font-semibold text-center text-slate-950">
          Step by Step Process
        </h2>
        <p className="self-center mt-5 text-lg leading-6 text-center text-slate-950 text-opacity-80 w-[952px] max-md:max-w-full">
          Ensure regulatory compliance with ease while enhancing your workflow
          efficiency. RIMBA's solutions are designed to help you meet standards
          faster and more accurately.
        </p>
        {steps.map((step, index) => (
          <ProcessStep key={index} {...step} />
        ))}
      </div>
    </section>
  );
};

export default ProcessSteps;
